version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8082:3000" # 외부 포트 8082, 컨테이너 내부 포트 3000

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8000" # 외부 포트 8081, 컨테이너 내부 포트 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
